PORT=/dev/ttyAMA0
APP=Tracker
TESTING=true
DEBUG=true

GPS_UUID=00000000-0000-0000-0000-000000000000
GPS_DEVICE_NAME=TEST_DEVICE_01
GPS_DEVICE_SERIAL=0000-0000-0000
GPS_UDP_HOST=0.0.0.0
GPS_UDP_TEST_HOST=127.0.0.1
GPS_UDP_PORT=9000
GPS_LAST_KNOWN_LOCATION_LAT=40.874786
GPS_LAST_KNOWN_LOCATION_LNG=-73.894813
GPS_LAST_KNOWN_LOCATION_TIME=0
GPS_PORT=/dev/cu.usbmodem1101


BASE_URL=https://localhost:8080
PORTS=/dev/ttyAMA0
OBD_PORT=/dev/cu.OBDII

FARE_COST=2
KEY=16ByteArray!4321
IV=16ByteArray!1234
BUS_ID=10
ROUTE=WESTERN_EAST_TO_WEST
COMPANY=Westline
